# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5662568926fa0d556a315b043f1990d552f920d88cf6e8727205dc290c05d0f41272de3fbb4b635308dfb74bd4710ab68523d7984600b819e899693992443fb3

test:
  secret_key_base: e4637d03964d58fcc088ab1fe316f017f80653d7d9853677339d63ae09246d63c33a36ae9f314e7011e30f9d3f661001a4e4d8d604ef9bd41072d125b64c73a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
